### ISSUE TITLE
Dashboard Auto Moderation Error

### ISSUE THREAD

**Issue by rfabricioflores** [saiteja-madha/discord-js-bot#268] opened 2022-12-05 09:52 UTC
**Description**
When submitting whitelisted channels in the dashboard it returns an error in the terminal

**To Reproduce**
1. Go to dashboard
2. Choose a channel in the "auto moderation form" and submit

**Expected behavior**
Add a channel or multiple to the whitelist channels

**Screenshots**
![image](https://user-images.githubusercontent.com/32011023/205605368-a3ee9819-fe4b-4020-b15e-8d2291d1eb0e.png)
![image](https://user-images.githubusercontent.com/32011023/205605832-f0c359c9-e134-493f-828b-ea4358d57f07.png)

**Versions**
 - NodeJS version: ^16.11.0
 - Bot version: 5.1.0

**Comment by saiteja-madha** [comment] 2022-12-09 21:32
Duplicate of #261

**Closed as completed by saiteja-madha** 2022-12-09 21:32 UTC
Labels: bug-unverified
